on:
  push:
    branches: main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.x

      - name: corepack
        run: |
          npm install --global corepack@latest
          corepack enable
        
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: pnpm run cy:run:ci

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            test-results.xml
